{% set name = "django-widget-tweaks" %}
{% set version = "1.4.3" %}
{% set sha256 = "bc645ef88307bc4ac269ee8ee9e572be814cd4a125c2bb6edb59ffcdc194982d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - django

test:
  imports:
    - widget_tweaks

about:
  home: https://github.com/jazzband/django-widget-tweaks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Tweak the form field rendering in templates, not in python-level form definitions.'

extra:
  recipe-maintainers:
    - scopatz
