travis:
  secure:
    BINSTAR_TOKEN: eyZPARkUtjdHc4mQ6dBR331IeVr8w59i40QqFD8YpYYIzcr+RV0DEFoXqgNcYl3PA8gOzHaQ2tvBny0zuH1jmnmCexcQBZD8Luo9AO0ohll/BFbzUjdLYUVMBTnBjt0/CPZEMfx0wPglNbmRAUpGjXeLvMJ0tWZISau3m9U5BFQprMtYAZ4U6/YitgqlCtoCZ7qIoapGtrsUFT48aj9ttqhQaXuCL3NbVxpNjd/NHxS/1KTqsZPaRRxLQbqGY9/Qb7ECcgIFNRkiOAvAiQqKj92kQS21T00Muu+QglyaVpaXFQLluP5Vw5BbEq2YZ/WObnHQxztc4r/sE+f+K10On2bQkHpMogLWubxFKOc6yak/m9oZcUKRR3oYsZB9grNJP8ySW9dt6OzA0T/emrhQ4I6gz0+SQHP9AftEcSufAQyIzSlq+EVd/BYKnPkSw84BBBx+v0iDaBo9LiSs9l0zDr6Qk7O5WClRbgyYoI2y0kzRRT/yybJMqIUDSITDCvcYY59VFiKK8I06ddvdVG4ga15++kwYqC+4t7Bs4PT2K0gmKNsVWKqOhN2Q0fOtti+XEsoHMNoFKisAc97g/bNduUUCfOQLKbNHkq2fbng9zCuFntk2dKWlfhDurPw4zyt90eFa86VmGZVJHuXg/DaMbIxrcpg3NOb2qDMr+reDIPE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
