travis:
  secure:
    BINSTAR_TOKEN: YUg3WNJHfOhywAKGBkfHQXyiOC7s/P0ftxjloVCm84e1Cbm2l/d6tGvbbfCPN8+g5WB+CZivTJnR2exoxDPjUb7KP1JPRiiFMTBMmqXzu7omrfggZ8+yQHGmldmeqIntIDaEzTGjfZNfOtrgNLyoUxufClW9pX4D4/4ZSsoCZpnvyDT1m4A9OSbZq2UjF73sS0aCTiQJJBS2yv9sDIUzTWRYUHQi/6tP8+V/AHFtMZIAnfDyy4ne6RT+VLoWqmMeQcchgFDNyYbq9vqS+LtUsm1TGCaN08oCHzDMiMQbnZVlIr1XqEjziM1aG7qryww3T7LUBQJiopfWxNP8RMJ96fOF//yysYLndBHZdynVh2TC+ilrEf7YTu4JyF8PrXLhssuH8rRUfT8nj9CPNMTEWCG1RR85j/+uxv5i82fZo1sKI98QdCtr/2BY3GWLTMPA1JB4p68370GgTGbBkrXw2jo7U+/hxu830acdxJC174J3wxyc5AUdpk/w1g6ve7piD3JQUKd/133LF20rcB8tfW4u4A3CrA9ZTnXf7LPaN6FCU7boWUdn2zD4avCyZUuGwd0SOjwzGi7my5df0SzfkD/2xFp7TUFNaFSkQgJ64EvdJl3lsC5VfQ+ehRkn4v9Qk1sJc3gM4BWtIQLCR1ir8K9QOxCmeo/4kXj48BNIFzo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
